### PR TITLE
Working backwards

### PR DESCRIPTION
**Pull request by 19aanand**
Working backwards to see how compatible dev and mutation data branch are

### CODE REVIEW

**Comment by kaczmarj** [comment]
something is wrong with this branch. many of these commits were already merged into development. what is the purpose of this pr

**Comment by 19aanand** [comment]
@kaczmarj We were trying to figure out how stale the combineClinicalAndMutationData branch is. The branch had some updates pushed to it, so I'll be closing this PR.

**Comment by kaczmarj** [comment]
you merged this pr? i don't think this should have been merged. it duplicates some commits and could cause some problems in the code base. can you revert the merge?

instead, we should find what changes were intended in the original PR, create a new branch from current dev, and then apply those changes in a new PR.

**Comment by kaczmarj** [comment]
for example `state.js` shows up in the commit diff, and that should definitely not happen. you might have merged an older state module for all we know.

**Comment by 19aanand** [comment]
Don't worry, they weren't merged into the development branch.

**Comment by kaczmarj** [comment]
oh i see the direction of the merge. my apologies. carry on !!!!!!!

**Comment by 19aanand** [comment]
This is an effort to make sure the combineClinicalAndMutationData branch is updated properly before merging its changes into development.

**Pull request merged**
