### PR TITLE
Violin plot x-axis labels

### PR DESCRIPTION
**Pull request by jmath908**
Modified violin plot x-axis labels to be rotated -45 degree.

### CODE REVIEW

**Comment by 19aanand** [comment]
It seems that the 2nd file changed has to do with creating a new webgen folder accidentally. Below is what the folder layout should look like when opening the repository in VS Code. Please make this update, and the pull request will be good to merge!

image

**Comment by kaczmarj** [comment]
@19aanand - it looks like a directory was added as a submodule. 

@jmath908 - did you use `git submodule` or something like that?

**Comment by kaczmarj** [comment]
@jmath908 - in https://github.com/web4bio/webgen/pull/347/commits/3f7b3520b3750a8c67c55aeb6c6fe7bc3bd974df , there are artifacts from a `git merge`. those shouldn't be there. stuff like `<<<<<< HEAD`. that should have been removed during the merge.

**Comment by jmath908** [comment]
@kaczmarj thank you. currently trying to rm the webgen submodule, not sure how it ended up there but its giving some issues.

**Comment by kaczmarj** [comment]
It might be easier to create a new branch from current development and then create a new PR with your changes. It can be really tedious to fix all these little things (from prior experience)

Best,
Jakub

**Pull request closed without merging**
